# Generated by Django 4.0.2 on 2022-02-05 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_order_user_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
